In [3]:
import requests
import os
from dotenv import load_dotenv
import pandas as pd
import plotly.express as px

load_dotenv()

True

In [4]:
#
api_key=os.getenv("api_key")


url = "https://alpha-vantage.p.rapidapi.com/query"

querystring = {"function":"TIME_SERIES_DAILY","symbol":"MSFT","outputsize":"compact","datatype":"json"}

headers = {
	"x-rapidapi-key": "29d04bb977msh6e6ccf157115028p116a36jsndf3231f7d1da",
	"x-rapidapi-host": "alpha-vantage.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

if response.status_code==200:
    data=response.json()
else:
    print(response.status_code)

df=pd.DataFrame(data)
df

,Meta Data,Time Series (Daily)
1. Information,"Daily Prices (open, high, low, close) and Volumes",NaN
2. Symbol,MSFT,NaN
3. Last Refreshed,2026-04-06,NaN
4. Output Size,Compact,NaN
5. Time Zone,US/Eastern,NaN
...,...,...
2025-11-14,NaN,"{'1. open': '498.2300', '2. high': '511.6000',..."
2025-11-13,NaN,"{'1. open': '510.3100', '2. high': '513.5000',..."
2025-11-12,NaN,"{'1. open': '509.3550', '2. high': '511.6700',..."
2025-11-11,NaN,"{'1. open': '504.8000', '2. high': '509.6000',..."
2025-11-10,NaN,"{'1. open': '500.0350', '2. high': '506.8500',..."

In [5]:
df = pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')

# 3. Clean the column names (removing "1. ", "2. ", etc.)
# Instead of '1. open', it becomes just 'open'
df.columns = [c.split('. ')[1] for c in df.columns]

# 4. Convert all columns to numeric (they come as strings from the API)
df = df.apply(pd.to_numeric)

# 5. Convert the index to actual Datetime objects
df.index = pd.to_datetime(df.index)
df

               open    high       low   close    volume
2026-04-06  373.490  373.73  369.5014  372.88  16146572
2026-04-02  367.205  373.64  364.1500  373.46  24099067
2026-04-01  373.490  373.99  368.2000  369.37  29417206
2026-03-31  364.550  372.90  363.0700  370.17  45244365
2026-03-30  361.895  365.36  356.2800  358.96  44797002
...             ...     ...       ...     ...       ...
2025-11-14  498.230  511.60  497.4400  510.18  28505746
2025-11-13  510.310  513.50  501.2900  503.29  25273114
2025-11-12  509.355  511.67  499.1201  511.14  26574851
2025-11-11  504.800  509.60  502.3488  508.68  17980020
2025-11-10  500.035  506.85  498.8000  506.00  26101480

[100 rows x 5 columns]

In [6]:
# Starting the EDA 
# 1. Inspecting the data structure
print("Here is the Structural info about the data : ")
print(df.info())
print("Inspecting the numerical summmary of the data :")
print(df.describe())

Here is the Structural info about the data :
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 100 entries, 2026-04-06 to 2025-11-10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    100 non-null    float64
 1   high    100 non-null    float64
 2   low     100 non-null    float64
 3   close   100 non-null    float64
 4   volume  100 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.7 KB
None
Inspecting the numerical summmary of the data :
             open        high         low       close        volume
count  100.000000  100.000000  100.000000  100.000000  1.000000e+02
mean   442.425900  446.365230  437.596185  441.924900  3.153996e+07
std     44.781526   45.050872   45.067529   45.629277  1.527615e+07
min    361.895000  362.450000  356.280000  356.770000  5.855880e+06
25%    400.585000  404.707500  396.030000  400.437500  2.367574e+07
50%    455.212500  463.720000  453.215000  458.020000  2.836987e+07
75%    483.415000  486.480000  477.905000  483.237500  3.684628e+07
max    510.310000  513.500000  504.910000  511.140000  1.288553e+08

In [7]:
# 2. INspecting the data quality , looking for  missing data or incorrect datatypes
print("-"*50)
print("Sumamry of data structure : ")
print(df.info())
print("Summary of the null values in DF : ")
print(df.isnull().sum())

--------------------------------------------------
Sumamry of data structure :
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 100 entries, 2026-04-06 to 2025-11-10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    100 non-null    float64
 1   high    100 non-null    float64
 2   low     100 non-null    float64
 3   close   100 non-null    float64
 4   volume  100 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.7 KB
None
Summary of the null values in DF :
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [9]:
# 3. inspecting the distribution in the data 
fig1=px.histogram(
    df,
    x="volume",
)
fig1.show()

fig2=px.histogram(
    df,
    x="open"
)
fig2.show()